name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # パッケージのキャッシュ
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path:
            node_modules
          key: ${{ runner.os }}-v3-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v3-dependencies-

      # Lintとテストの実行
      - name: npm install, build
        run: |
          export NODE_OPTIONS="--max-old-space-size=1024"
          npm ci
          npm run prebuild
          npm run build:ci

      # ビルドの実行
      - name: app build
        run: |
          npm run build-site

      # デプロイ
      - name: deploy
        run: |
          npx netlify-cli deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --dir www/ \
            --auth ${{ secrets.NETLIFY_TOKEN }} \
            --prod
