name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: prepare code
        run: git clone https://github.com/ionic-jp/community-site.git site

      # community-siteのビルド
      - name: community-site build
        run: |
          npm install
          npm run build.ci
        working-directory: site

      # Docsのビルド
      - name: npm install, build
        run: |
          npm ci --legacy-peer-deps
          npm run prebuild
          npm run build:ci
          mv site/www/* www/

      # デプロイ
      - name: deploy
        run: |
          npx netlify-cli deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --dir www/ \
            --auth ${{ secrets.NETLIFY_TOKEN }} \
            --prod
